require('plugins')
require('options')
require('keymaps')
require('colorscheme')

-- Plugins config files
require('configs.cmp')
require('configs.lsp')
require('configs.bufferline')
require('configs.git-signs')
require('configs.lualine')
require('configs.comment')
require('configs.nvimtree')
require('configs.autopairs')
require('configs.toggleterm')
require('configs.treesitter')
require('configs.indent-blankline')
require('configs.lsp-signature')
